package com.everywhere.trip.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.everywhere.trip.bean.BanmiEntity;

import com.everywhere.trip.dao.BanmiEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig banmiEntityDaoConfig;

    private final BanmiEntityDao banmiEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        banmiEntityDaoConfig = daoConfigMap.get(BanmiEntityDao.class).clone();
        banmiEntityDaoConfig.initIdentityScope(type);

        banmiEntityDao = new BanmiEntityDao(banmiEntityDaoConfig, this);

        registerDao(BanmiEntity.class, banmiEntityDao);
    }
    
    public void clear() {
        banmiEntityDaoConfig.clearIdentityScope();
    }

    public BanmiEntityDao getBanmiEntityDao() {
        return banmiEntityDao;
    }

}
